- name: Join k8s command
  become: true
  hosts: masters
  tasks:
    - name: Get join command
      ansible.builtin.command:
        cmd: kubeadm token create --print-join-command
      register: kubeadm_join_command
      changed_when: false
    - name: Display join command
      ansible.builtin.debug:
        var: kubeadm_join_command

- name: Join k8s cluster
  hosts: workers
  become: true
  tasks:
    - name: Set join command
      ansible.builtin.set_fact:
        kubeadm_join_command: "{{ hostvars['master']['kubeadm_join_command']['stdout_lines'][0] }}"
    - name: Join k8s cluster
      ansible.builtin.command:
        cmd: "{{ kubeadm_join_command }}"
      register: kubeadm_join_result
      changed_when: false
    - name: Display join result
      ansible.builtin.debug:
        var: kubeadm_join_result
